In [7]:
# 학습 날짜 23.03.22(수) 넘파이
import numpy as np
# array는 배열을 의미

In [8]:
arr1 = np.array([0, 2, 5.5, 7])
print(arr1)

[0.  2.  5.5 7. ]


In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(5,)

In [13]:
arr.dtype

dtype('float64')

In [14]:
arr = np.zeros(shape = (6,2)) # 배열 초기화
for i in range(6):
    arr[i] = (i, i)
arr

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,), dtype = int) # 5, 안하고 5만 해도 됨! 

array([1, 1, 1, 1, 1])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((2, 2))

array([[0. , 2. ],
       [5.5, 7. ]])

In [19]:
np.empty((2, 2), dtype = int)

array([[                  0, 4611686018427387904],
       [4617878467915022336, 4619567317775286272]])

In [20]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
np.eye(3, k = 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [22]:
np.linspace(2.0, 3.0, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [23]:
np.linspace(2.0, 3.0, num = 5, endpoint = False) # false 소문자 안됨!

array([2. , 2.2, 2.4, 2.6, 2.8])

In [24]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [25]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [26]:
arr.shape

(5,)

In [27]:
np.arange(3, 9, 2)

array([3, 5, 7])

In [28]:
arr[2] = 10
arr

array([ 0,  1, 10,  3,  4])

In [29]:
arr[3] = 'jin'

ValueError: invalid literal for int() with base 10: 'jin'

In [30]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
arr.shape

(3, 4)

In [32]:
arr.reshape(-1) # 원래 1차원으로 바꿔줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
arr.ravel() # 다차원을 1차원으로 보여주는 함수

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr.reshape(-1 ,1) # 행과 열, -1은 알 수 없다는 뜻

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [35]:
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
arr = np.array([[0, 1, 2], # arange와 array의 차이는?
               [3, 4, 5]])
type(arr)

numpy.ndarray

In [38]:
arr.shape

(2, 3)

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11]],
                
                [[12, 13, 14, 15],
                 [16, 17, 18, 19],
                 [20, 21, 22, 23]]])
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
arr.ndim # 속성 확인하기

3

In [42]:
arr.shape # 면 2개 행 3개 열 4개

(2, 3, 4)

In [43]:
arr.size

24

In [44]:
arr.dtype # 원래 int32 나와야하는데? - 54p 나중에 다시 확인 ㄱ

dtype('int64')

In [45]:
arr.itemsize # 요소 크기 확인

8

In [46]:
arr.strides # 면, 행, 열인데 다 2배씩 차이가 남! [프로그램 혹은 버전 차이 인듯?]

(96, 32, 8)

In [47]:
a = np.float32(5.0)
a

5.0

In [48]:
type(a)

numpy.float32

In [49]:
b = np.int_([1, 2, 3]) # numpy.dtypes 클래스의 구성은 좀 다양함 - 55p
b

array([1, 2, 3])

In [50]:
type(b)


numpy.ndarray

In [51]:
c = np.arange(5, dtype = np.uint16)
c

array([0, 1, 2, 3, 4], dtype=uint16)

In [52]:
type(c)

numpy.ndarray

In [53]:
dt = np.dtype('>i4')
dt

dtype('>i4')

In [54]:
dt.byteorder

'>'

In [55]:
dt.itemsize

4

In [56]:
dt.name

'int32'

In [57]:
dt.type is np.int32

True

In [58]:
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2, ))])
dt

dtype([('name', '<U16'), ('grades', '<f8', (2,))])

In [59]:
dt['name']

dtype('<U16')

In [60]:
dt['grades']

dtype(('<f8', (2,)))

In [61]:
arr = np.array([('jin', 25, 67), ('suho', 18, 77)],
               dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
arr

array([('jin', 25, 67.), ('suho', 18, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [63]:
arr[1]

('suho', 18, 77.)

In [64]:
arr['age']

array([25, 18], dtype=int32)

In [65]:
np.dtype([('a', 'f4'), ('b', np.float32), ('c', 'f4', (2, 2))])

dtype([('a', '<f4'), ('b', '<f4'), ('c', '<f4', (2, 2))])

In [66]:
np.dtype([('a', 'f4'), ('', 'i4'), ('c', 'i8')])

dtype([('a', '<f4'), ('f1', '<i4'), ('c', '<i8')])

In [67]:
np.dtype('i8, f4, S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [68]:
np.dtype('3int8, float32, (2, 3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [69]:
np.dtype({'names' : ['col1', 'col2'], 'formats' : ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [70]:
np.dtype({'names' : ['col1', 'col2'],
          'formats' : ['i4', 'f4'],
          'offsets' : [0, 4],
          'itemsize' : 12})

dtype({'names': ['col1', 'col2'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 12})

In [71]:
np.dtype({'col1' : ('i1', 0), 'col2' : ('f4', 1)})

dtype([('col1', 'i1'), ('col2', '<f4')])

In [72]:
c = np.dtype([('a', 'i8'), ('b', 'f4')])
c.names

('a', 'b')

In [73]:
c.fields

mappingproxy({'a': (dtype('int64'), 0), 'b': (dtype('float32'), 8)})

In [74]:
def print_offsets(d) :
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize:", d.itemsize)
    
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2'))

offsets: [0, 1, 2, 6, 7, 15]
itemsize: 17


In [75]:
d = np.dtype('u1, u1, i4, u1, i8, u2')
d

dtype([('f0', 'u1'), ('f1', 'u1'), ('f2', '<i4'), ('f3', 'u1'), ('f4', '<i8'), ('f5', '<u2')])

In [76]:
d.itemsize

17

In [77]:
d.fields

mappingproxy({'f0': (dtype('uint8'), 0),
              'f1': (dtype('uint8'), 1),
              'f2': (dtype('int32'), 2),
              'f3': (dtype('uint8'), 6),
              'f4': (dtype('int64'), 7),
              'f5': (dtype('uint16'), 15)})

In [78]:
d.names

('f0', 'f1', 'f2', 'f3', 'f4', 'f5')

In [79]:
d.fields['f0']

(dtype('uint8'), 0)

In [80]:
d.fields['f0'][1]

0

In [81]:
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2', align = True))

offsets: [0, 1, 4, 8, 16, 24]
itemsize: 32


In [82]:
x = np.dtype([(('my title', 'name'), 'f4')])
x.fields

mappingproxy({'name': (dtype('float32'), 0, 'my title'),
              'my title': (dtype('float32'), 0, 'my title')})

In [83]:
x.names

('name',)

In [84]:
np.dtype({'name' : ('i4', 0, 'my title')})

dtype([(('my title', 'name'), '<i4')])

In [86]:
a = np.array([(1, 2, 3), (4, 5, 6)], dtype = 'i8, f4, f8')

a[1]

(4, 5., 6.)

In [87]:
a

array([(1, 2., 3.), (4, 5., 6.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [88]:
a = np.zeros(2, dtype = 'i8, f4, ?, S1')
a

array([(0, 0., False, b''), (0, 0., False, b'')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [89]:
a[:] = 7
a

array([(7, 7.,  True, b'7'), (7, 7.,  True, b'7')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [90]:
a[:] = np.arange(2)
a

array([(0, 0., False, b'0'), (1, 1.,  True, b'1')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [91]:
a = np.zeros(3, dtype = [('a', 'i8'), ('b', 'f4'), ('c', 'S3')])

In [92]:
b = np.ones(3, dtype = [('x', 'f4'), ('y', 'S3'), ('z', '0')])
# 이거 계속 오류 남!! 왜인지 모르겠음 - 66p
b[:] = a
# 위에 해결 되면 이것도 가능해짐
b

TypeError: data type '' not understood

In [93]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr2 = np.arange(9).reshape(3, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
arr3 = np.reshape(np.arange(24), (2, 3, 4))
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [96]:
arr3[1, 1, 2]

18

In [97]:
arr3[1][2][3]

23

In [98]:
arr1[1]

1

In [99]:
arr1[:6]

array([0, 1, 2, 3, 4, 5])

In [100]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [101]:
arr1[::2]

array([0, 2, 4, 6, 8])

In [102]:
arr1[1::2]

array([1, 3, 5, 7, 9])

In [103]:
arr1[1:7:2]

array([1, 3, 5])

In [104]:
arr1[-3:9]

array([7, 8])

In [105]:
arr1[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [108]:
arr1[-3:2:-1]

array([7, 6, 5, 4, 3])

In [109]:
# 인덱스 시작이 종료보다 크면 길이가 0인 객체가 반환된다.
arr1[5:2]

array([], dtype=int64)

In [110]:
arr1[5:]

array([5, 6, 7, 8, 9])

In [111]:
arr2[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [112]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
arr2[:2, :2]

array([[0, 1],
       [3, 4]])

In [114]:
arr2[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [116]:
arr2[:, :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
arr2[1, :]

array([3, 4, 5])

In [118]:
arr2[1,2]

5

In [119]:
arr3[0, :, 1]

array([1, 5, 9])

In [120]:
arr3[1, :, :]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [122]:
arr3[:2, 1:, :2]

array([[[ 4,  5],
        [ 8,  9]],

       [[16, 17],
        [20, 21]]])

In [123]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [125]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
arr[[0, 1, 2], [0, 1, 0]]
# [행들] [열들] -> 0행 0열 값, 1행 1열 값, 2행 0열 값

array([1, 4, 5])

In [128]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
arr[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
# 1p ~ 71p 고급인덱싱까지 함!